# Generated by Django 6.0.6 on 2026-06-25 18:37

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Application name", max_length=250),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief application description"
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("hero", models.ImageField(blank=True, upload_to="heroes/")),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Is this application active?"
                    ),
                ),
                (
                    "shown",
                    models.BooleanField(
                        default=False, help_text="Is this application visible?"
                    ),
                ),
                (
                    "code_repo_url",
                    models.URLField(
                        blank=True, help_text="Code repository location", max_length=250
                    ),
                ),
                (
                    "design_documentation_url",
                    models.URLField(
                        blank=True,
                        help_text="Design documentation location",
                        max_length=250,
                    ),
                ),
                (
                    "platform_description",
                    models.TextField(
                        blank=True, help_text="Brief description of platform used"
                    ),
                ),
                (
                    "deployment_env_further_details",
                    models.TextField(
                        blank=True,
                        help_text="Further details about the deployment environment",
                    ),
                ),
                (
                    "date_released",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Approximate date the application was released",
                    ),
                ),
                (
                    "date_decommissioned",
                    models.DateField(
                        blank=True,
                        help_text="Approximate date the application was decommissioned",
                        null=True,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "display_priority",
                    models.IntegerField(
                        blank=True,
                        default=10,
                        help_text="Display priority (lower numbers shown at the top)",
                    ),
                ),
                (
                    "incomplete_info",
                    models.BooleanField(
                        default=True, help_text="Application needs more information?"
                    ),
                ),
                (
                    "ast_round",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="AST round involved with when the app was created",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["display_priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the organization", max_length=250
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("icon", models.ImageField(blank=True, null=True, upload_to="icons/")),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the application component (include version if relevant)",
                        max_length=250,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Further details for the application component",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "applications",
                    models.ManyToManyField(blank=True, to="tools.application"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="application_components",
            field=models.ManyToManyField(blank=True, to="tools.applicationcomponent"),
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the dataset", max_length=250),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the dataset"
                    ),
                ),
                ("url", models.URLField(blank=True, help_text="Dataset location")),
                (
                    "credentials",
                    models.TextField(
                        blank=True, help_text="Credentials for accessing the dataset"
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "applications",
                    models.ManyToManyField(blank=True, to="tools.application"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="datasets",
            field=models.ManyToManyField(blank=True, to="tools.dataset"),
        ),
        migrations.CreateModel(
            name="DeploymentEnvironment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the deployment environment", max_length=250
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the deployment environment",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "applications",
                    models.ManyToManyField(blank=True, to="tools.application"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="deployment_environment",
            field=models.ManyToManyField(blank=True, to="tools.deploymentenvironment"),
        ),
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the developer", max_length=250),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Square image, minimum 150px × 150px",
                        null=True,
                        upload_to="icons/",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Is the developer active?"
                    ),
                ),
                (
                    "applications",
                    models.ManyToManyField(blank=True, to="tools.application"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tools.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="developers",
            field=models.ManyToManyField(
                blank=True, related_name="developers", to="tools.developer"
            ),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback_entry", models.TextField()),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        default=datetime.date.today,
                        help_text="Date feedback reported",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "application",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tools.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(blank=True, help_text="Link location")),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Link description", max_length=250
                    ),
                ),
                (
                    "additional_description",
                    models.TextField(
                        blank=True, help_text="Further details for the link"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tools.application",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_entry", models.TextField()),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        default=datetime.date.today,
                        help_text="Date issue or milestone happened",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tools.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that developed the application",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tools.organization",
            ),
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the region", max_length=250),
                ),
                (
                    "accronym",
                    models.CharField(
                        blank=True, help_text="Region acronym", max_length=4
                    ),
                ),
                (
                    "organization",
                    models.ManyToManyField(blank=True, to="tools.organization"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="region",
            field=models.ManyToManyField(blank=True, to="tools.region"),
        ),
        migrations.CreateModel(
            name="Scientist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the scientist", max_length=250),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Square image, minimum 150px × 150px",
                        null=True,
                        upload_to="icons/",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Is the scientist active?"
                    ),
                ),
                (
                    "applications",
                    models.ManyToManyField(blank=True, to="tools.application"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tools.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="ast_pi",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="PI Scientist when the application was developed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="PI_Scientist",
                to="tools.scientist",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="scientists",
            field=models.ManyToManyField(blank=True, to="tools.scientist"),
        ),
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the service area", max_length=250
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "service_catalog_url",
                    models.URLField(
                        blank=True, help_text="Reference to the SERVIR Service catalog"
                    ),
                ),
                ("icon", models.ImageField(blank=True, null=True, upload_to="icons/")),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "applications",
                    models.ManyToManyField(blank=True, to="tools.application"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Service Name", max_length=250)),
                ("description", models.TextField(blank=True)),
                (
                    "service_catalog_url",
                    models.URLField(
                        blank=True, help_text="Reference to the SERVIR Service catalog"
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "service_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tools.servicearea",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Primary URL of the application",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Application name", max_length=250),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description. Why is the app relevant for SERVIR?",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ExternalApps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "serviceareas",
                    models.ManyToManyField(blank=True, to="tools.servicearea"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="serviceareas",
            field=models.ManyToManyField(blank=True, to="tools.servicearea"),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tools.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "application")},
            },
        ),
    ]
