# Generated by Django 6.0.6 on 2026-06-25 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="region",
        ),
        migrations.RemoveField(
            model_name="service",
            name="service_area",
        ),
        migrations.RemoveField(
            model_name="servicearea",
            name="applications",
        ),
        migrations.RemoveField(
            model_name="application",
            name="serviceareas",
        ),
        migrations.RemoveField(
            model_name="externalapp",
            name="serviceareas",
        ),
        migrations.DeleteModel(
            name="Region",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
        migrations.DeleteModel(
            name="ServiceArea",
        ),
    ]
