# Generated by Django 6.0.6 on 2026-06-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0002_remove_application_region_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalapp",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Brief description. Why is the app relevant for EarthRISE?",
            ),
        ),
    ]
