# Generated by Django 6.0.6 on 2026-08-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0003_alter_externalapp_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="hero_credit",
            field=models.CharField(
                blank=True,
                help_text="Image credit / attribution shown on the thumbnail",
                max_length=250,
                null=True,
            ),
        ),
    ]
